### PR TITLE
gitignore, null/undefined values in editorconfig, and some formatting [wip]

### PR DESCRIPTION
**Pull request by slang800**
that part about the null/undefined values being returned as strings should probably get a test case...

### CODE REVIEW

**Comment by jedmao** [comment]
Why do you find it necessary to change the indentation on every project you touch from tabs to spaces? You are the very reason projects like this exist in the first place. You have your own preferences and you like to force them on other people. If you didn't already read [Tabs vs. Spaces, We Meet Again](http://jedmao.ghost.io/2014/08/20/tabs-vs-spaces-the-age-old-war/), which I linked you before, I strongly suggest you do so. For all our sakes, don't skip a paragraph. Spaces for indentation are the very reason it's impossible to infer or enforce indentation on a project and yet you try to slip them in everywhere you see fit. You clearly don't understand the implications, even though [you claim understand](https://github.com/slang800/editorconfig-tools/issues/12#issuecomment-77001208).

Seriously. Read the blog post. The whole thing. Then get back to me.

**Comment by slang800** [comment]
> Why do you find it necessary to change the indentation on every project you touch from tabs to spaces?

I'm going to assume "every project" is intended as a hyperbole, and skip right to talking about this particular project. I did not change the indentation of this project: I changed the indentation of the only inconsistent file in this project to match the rules of the rest of the project. It is not my preference for a particular indentation style - it is my desire for _consistency_.

Also, I read your blog post. Your arguments make sense, but you don't take into account how prevalent alignment in source code actually is. For example, the file that we are talking about contained no alignment what-so-ever. Thus, changing the indentation type doesn't cause any issues.

If you were arguing for the conversion of this entire project over to tabs then I could see your point, but keeping one file as tabs while the rest are indented with spaces seems like needless complexity.

> You have your own preferences and you like to force them on other people

If you haven't already read [The Correspondence Bias](http://www.wjh.harvard.edu/~dtg/Gilbert%20&%20Malone%20(CORRESPONDENCE%20BIAS).pdf), I strongly suggest you do so. Seriously. Read the essay. The whole thing. Then you should have a solid understanding of how to interpret people's actions without letting the correspondence bias get the best of you.

**Comment by jedmao** [comment]
Yep. I knew I would regret saying anything the moment I posted it. I swear I'm seeing things (or only what I wanted to see) when I saw the removal of `indent_style = tab` from the .editorconfig file. Anyway, my apologies for losing it. It came after reading your commit messages like [eww, visual studio](https://github.com/slang800/editorconfig-tools/commit/a31eae21b110106f0f49bb398032cd16f5b30d4b), [better .editorconfig](https://github.com/slang800/editorconfig-tools/commit/995c8875fd2628a9c02dc80eb76ea4a1c56fbdb0) (replacing tabs with spaces) and [purge bad code](https://github.com/slang800/editorconfig-tools/commit/c2b155768a96ace1a2bcb51a47c7efc80fb149f4), so I wasn't in the best of moods. If nothing else, it motivated me to finish that project. At least, I've given it some love recently.

I'm also very much in favor of consistency above all else and to that point, your PR looks great.

I'll definitely read The Correspondence Bias when it's not 3:19 AM. Looks like a lengthy read.

**Comment by slang800** [comment]
Ah, that’s understandable. Sorry about those commit messages, especially if they seemed like a personal attack - that certainly wasn't the intent.

**Pull request merged**
